### ISSUE TITLE
Support Building/Packaging on Amazon Linux

### ISSUE THREAD

**Issue by apldev3** [nsacyber/HIRS#102]
As discussed in #97, building/packaging on Amazon Linux (specifically the TPM 2.0 Provisioner) doesn't work as easily as it does on CentOS7. There appears to be an issue with either CMake or Make on the Amazon Linux platform. This ticket is meant to track work done towards finding a workaround or updating the build file in such a way that building/packaging HIRS is supported on Amazon Linux platforms.

With the merge of #97, installing an RPM built in CentOS7 should work, so nothing should need done there.

**Comment by iadgovuser26** [comment]
This issue is being retired as no other comments in support of this feature has been entered.
