### ISSUE TITLE
Create a Validity Check method for Platform Certs

### ISSUE THREAD

**Issue by iadgovuser26** [nsacyber/HIRS#108]
The V1.1 version of the Platform Certificate Profile added a new concept of "Delta" Platform certificate which can be created after the initial (base) Platform certificate is created.  A new Validity check capability will be needed that collects all the Platform Certificates associated with a device (the "Platform Certificate Chain") and process them to determine if the set is valid or invalid. The actual individual validity checks will be added as separate issues. This issue only address the creation of the method to support individual validity checks. 

The validity check is performed only if the check platform attributes policy is checked.
If the  Platform Certificate set is considered invalid, the processing of the certificate should fail and an attestation certificate should NOT be issued.
If the Platform Certificate set is considered valid then the processing of the certificate can continue.

**Comment by chubtub** [comment]
I've identified HIRS_AttestationCA.hirs.attestationca.service.SupplyChainValidationServiceImpl as the most appropriate class for the new validation method.  Generally speaking, I will reference the following:

1. HIRS_Utils.hirs.persist.CertificateSelector has a member method byHolderSerialNumber() that matches platform certificates by their holder fields.
2. HIRS_Utils.hirs.data.persist.certificate.attributes.ComponentIdentifier has the following getters:
- getComponentManufacturer()
- getComponentModel()
- getFieldReplaceable()
- getComponentSerial()
3. HIRS_Utils.hirs.data.persist.certificate.attributes.V2.ComponentIdentifierV2 from another branch has the following getters:
- getAttributeStatus()
- getComponentClass()

**Comment by cyrus-dev** [comment]
As I spoke earlier, I think creating a new class should be done called PlatformChainValidator (PCV).  Where the SupplyChainCredentialValidator (SCCV) is used to validate platform cert to EK then through multi CAs to the root, the PCV would be a sub set that validates the multi platform of the base and deltas.  This would also be helpful in keeping v1 certs separate from v2 code wise for readability.

Also I'm currently looking at the SCCV and the interface CredentialValidator to see about refactoring to pull generic utility methods out and then the PCV would be another child for the CredentialValidator.  So then the SCCV is used to validate the base to the root CA and the PCV is used to validate the delta to the base post base validation.

**Comment by chubtub** [comment]
There is a TCG Attribute OID, tcgCredentialType, that is required in the new spec.  It would make distinguishing base credentials from deltas easy in the new supply chain method.
