### ISSUE TITLE
tpm_aca_provision detects a TPM 2.0 device as 1.2 and does not allow a provision to occur

### ISSUE THREAD

**Issue by apldev4** [nsacyber/HIRS#119]
@iadgovuser26 reported:

When issuing a tpm_aca_provision I get the following error
sudo tpm_aca_provision
TPM 1.2 detected.
The package 'HIRS_Provisioner_TPM_1_2' must be installed to provision a TPM 1.2.

However when I look at dmesg I see a 2.0 device:
dmesg | grep TPM
[ 0.000000] ACPI: TPM2 000000007aade618 00034 (v03 DELL CBX3 00000001 AMI 00000000)

When i use hirs-provisioner -p the process works.

**Comment by apldev4** [comment]
From looking at the output you've provided from dmesg, it is clear to a human that the TPM is a 2.0 TPM. However, the tpm_aca_provision script expects TPM 2.0 devices to have the string "TPM 2.0" in the dmesg output. That is because that script was written based on too few examples of dmesg outputs, /sys/class/tpm files, and TPM emulators. The reason the script is telling you that your device is a 1.2 device is because it sees tpm_version on the path. That is not a very good way to determine what version of TPM you have. Nothing stops a person from installing a package with a tool called tpm_version on a machine with the wrong TPM. The tpm_aca_provision script is an accident waiting to happen. By the time a user has installed a HIRS provisioner package (1.2 or 2.0) so that they have the tpm_aca_provision script available, they should not be wondering at that point which TPM version they have.

Secondly, if the correct version of the TPM Provisioner is installed, the user should always use the command hirs-provisioner provision, because it will be the same regardless of the version.

Rather than extending the life of the tpm_aca_provision script and the maintenance nightmare it invites, we should remove it and update the documentation accordingly. The documentation should be updated with suggestions for commands a user can run to figure out what version of TPM he or she has.

Thoughts?

**Comment by apldev4** [comment]
@iadgovuser26 replied:


I  would prefer keeping the tpm_aca_provision since it follows the  convention used by TPM tools. Perhaps separating it  into  tpm_aca_provision and tpm2_aca_provision will work.

**Comment by apldev4** [comment]
The error prone part is the guessing at what version of TPM is present. Without that, `tpm_aca_provision` (and `tpm2_aca_provision`) would simply a single line that calls `hirs-provisioner provision`. Are you saying you just want people to be able to type `tpm_aca_provision` or `tpm2_aca_provision` rather than typing `hirs-provisioner provision`?

**Comment by iadgovuser26** [comment]
If we cant come up with a maintainable way to detect a TPM 2.0 vs 1.2 , then yes tpm2_aca_provision is preferable to hirs-provisioner provision.

**Comment by apldev4** [comment]
@iadgovuser26 
In your creation of the issue, you say your ran `dmesg | grep TPM`. The installation notes say to figure out what version of TPM you have so you can install the right provisioner, you should run `dmesg | grep -i tpm_tis`. I'm not sure what the `tis` is all about, but the case-insensitivity could be an issue. Could you run `dmesg | grep -i tpm_tis` and post the output here?
Thank you.
