### ISSUE TITLE
Create initial system test for Delta Platform Certificates

### ISSUE THREAD

**Issue by iadgovuser26** [nsacyber/HIRS#132]
Create a system test for testing a Base certificate and 2 Delta Platform Certificates.

The Base Certificate should include the usual components: processor, baseboard, disk, memory, nic, and bios (left out chassis).
Delta 1 should remove a disk and replace it with a different model.
Delta 2 should remove a memory stick ad replace it with a different model.

**Comment by busaboy1340** [comment]
Using the TPM 2.0 Emulator, the PACCOR tool currently generates the components listed below. (In file /var/hirs/pcgeneration/componentsFile)

{
    
    "PLATFORM": {
        "PLATFORMMANUFACTURERSTR": "Not Specified","PLATFORMMODEL": "Not Specified","PLATFORMVERSION": "Not Specified"
    },
    "COMPONENTS": [
        {
            "MANUFACTURER": "Not Specified","MODEL": "Not Specified"
        },
        {
            "MANUFACTURER": "Not Specified","MODEL": "Not Specified","FIELDREPLACEABLE": "false"
        },
        {
            "MANUFACTURER": "Not Specified","MODEL": "BIOS"
        }
    ],
    "PROPERTIES": [
        {
            "NAME": "uname -r",
            "VALUE": "3.10.0-957.12.1.el7.x86_64"
        },
        {
            "NAME": "OS Release",
            "VALUE": "CentOS Linux 7 (Core)"
        }
    ]
}

**Comment by busaboy1340** [comment]
Merged in initial system test for a bad base certificate with PR #170 
Maybe keep this issue open for follow on Delta system tests? 
Or close this issue and open a new one?

**Comment by busaboy1340** [comment]
Agreed to close this and add follow on Delta systems tests with additional issues.
Closed by PR #170
