### ISSUE TITLE
Update HIRS_Provisioner config documentation

### ISSUE THREAD

**Issue by m-morrone** [nsacyber/HIRS#150]
In previous releases of the HIRS_Provisioner, hirs-provisioner-tpm2 included a config option that would check for /etc/hirs/hirs-site.config and generate it if needed.  This appears to have been removed from the hirs-provisioner-tpm2 but hirs-provisioner is now installed as well by HIRS_Provisioner_TPM_2_0, which provides this functionality.  The documentation at https://github.com/nsacyber/HIRS/wiki/installation_notes#provisioner-setup shows separate commands for TPM1.2 and TPM2.0 but these should now both use the same command, sudo hirs-provisioner -c.

**Comment by apldev3** [comment]
Moreover than what you're suggesting, they can both now just make use of the `hirs-provisioner` command to do the provisioning. If you invoke the `hirs-provisioner` command after installing the HIRS_ProvisionerTPM2, then it should detect that you installed that version as opposed to the older HIRS_Provisioner for TPM 1.2.

**Comment by apldev3** [comment]
Actually the `hirs-provisioner provision` command is wrapped by the `tpm_aca_provision` script that is installed by default for both provisioners. The latter should be favored and is the one referenced in the Wiki rather than direct invocation of the `hirs-provisioner provision` command.

**Comment by apldev3** [comment]
At any rate I think this has been sufficiently taken care of. @m-morrone feel free to reopen and comment if it's not to your liking.
