### ISSUE TITLE
Allow ACA to perform Validations without issuing a AIC

### ISSUE THREAD

**Issue by iadgovuser26** [nsacyber/HIRS#169]
Allow ACA to perform Validations without issuing a AIC (Provide automated AIC update as well):
    a. Allow admins to set the Validity period (currently fixed at 10 years). Add to Policy Page.
    b. Allow admins to set AIC update window in which a new AIC will be issued when a provisioning request is made and the existing AIC (in the ACA DB) will expire within that window. Add to Policy Page?
    c. The ACA needs to check if an AIC request is not within the window that the AIC fields required for the current policy settings are missing (e.g. Require A EC validation is set , but no TPM Manufacturer or Model number is in the current AIC.). This could be controlled by a new policy setting"
    d. May need to update client to support new command for system check or add logic to skip AIK generation.

**Comment by cyrus-dev** [comment]
For section d. that can be handled at ACA level, it'll just ignore since it already knows the state of the established Issued Certificate.

**Comment by iadgovuser26** [comment]
New Policy page item should be: Attestation Certificate Generation: options 
The option dialogue should show the following (radio button) options (allow only 1 to be selected): 
* Never generate an Attestation Certificate
* Always Generate an Attestation Certificate or  
* Only Generate when current Attestation Certificate expires
With an input box which sets the Number of days. Input box text should read:
* Validity period for the Attestation Certificate [days ]
Where days defaults to 3650 (ten years). The input box should be greyed out when Never is selected.
