### ISSUE TITLE
ACA provsioning Platform Attributes pass when platform cert not found.

### ISSUE THREAD

**Issue by iadgovuser26** [nsacyber/HIRS#21]
When testing the platform validation process found a condition where the Platform Cert wasn't loaded but the Attributes seemed to pass.

Another condition where this possible is if the Platform cert was loaded but the signature was invalid (e.g. the Platform Certs Trust Chain is missing) then this case could be possible. The error indicated by hovering over the Platform cert red circle indicated that "cant validate a platform cert without a trust store". 

Proposed solution: Platform Attributes should not pass if the Platform Certificate is invalid. This implies that the EK certificate needs to be valid as well.

**Comment by apldev3** [comment]
MR #21 was merged. Closing this now.
