### ISSUE TITLE
Add support for processing of PC Client Event Log structures

### ISSUE THREAD

**Issue by iadgovuser26** [nsacyber/HIRS#245]
In support of issue #238 , a basic ability to process PC Client Event Log structures is needed.
This requires Issue #242 Add UEFI variable processing for TCG Event Log. PC Client Event Log structures are defined in the [PC Client Platform Firmware Profile (PFP)](https://trustedcomputinggroup.org/wp-content/uploads/TCG_PCClientSpecPlat_TPM_2p0_1p04_pub.pdf).

**Comment by cyrus-dev** [comment]
@iadgovuser26 Is there any reason that this section of code couldn't be moved to the ACA module?

**Comment by iadgovuser26** [comment]
Corrected the initial comment to show a dependency with #242 which is part of HIRS Utils.

**Comment by iadgovuser26** [comment]
This issue  will enable processing of individual events within the TCG Event Log. The basic purpose of this capabality will be to provide details for failed Firmware validations. It relies on the UEFI structure parsing provided in Issue #242.  Several more issues are needed to weave in the TCG Log processing when a firmware validation fails and provide human readable details about which firmware component failed.
