### ISSUE TITLE
OID class missing log entry.

### ISSUE THREAD

**Issue by iadgovuser26** [nsacyber/HIRS#266]
HIRS_AttestationCA_Portal.log has the following entry:
[hirs.data.persist.certificate.PlatformCredential.getAllAttributes] WARN  : No class defined for attribute with OID: 2.23.133.2.25.

**Comment by cyrus-dev** [comment]
Upon investigation, the OID is handled in a different part of the code.  There just isn't a case in the getAllAttributes method to handle this like there is for 2.23.133.2.17.
