### ISSUE TITLE
Create Docker Container for TPM 1.2

### ISSUE THREAD

**Issue by cyrus-dev** [nsacyber/HIRS#292]
PR #289 highlighted there was no testing of the code changes on a 1.2 system.  The focus has been on TPM 2.0 for firmware validation.  

This issue should spawn 2 PRs, 1) to make the changes and create the scripts for a TPM 1.2 container (client), 2) update branch for firmware validation on a 1.2 machine (server).

**Comment by iadgovuser26** [comment]
Docker image for tpmprovisioner can be found on [Dockerhub](https://hub.docker.com/r/hirs/hirs-ci/tags). This image contains has the tpm emulator for TPM v 1.2. The  Dockerfile can be found [here](https://github.com/nsacyber/HIRS/blob/master/.ci/docker/Dockerfile.tpmprovisioner).
