### ISSUE TITLE
ACA fails if issuer subject does not include organization (O=)

### ISSUE THREAD

**Issue by mwiseman32** [nsacyber/HIRS#308]
Testing using the swtpm (https://github.com/stefanberger/swtpm) ACA fails because it is requiring an Organization in the Subject even though the Organization is not printed as part of the subject, only the cn.
Error from HIRS_AttestationCA.log:
2020-10-22 12:36:02 [hirs.attestationca.rest.AttestationCertificateAuthorityExceptionHandler.handleExpectedExceptions] ERROR : The ACA has encountered an expected exception: organization cannot be null or empty.

Tested using:
Fedora 32 as host OS
KVM
installed swtpm-tool from standard repo
Tested using sw TPM 1.2 but no reason to expect also not applicable to sw TPM 2.0.

Work around is to force swtpm-tools to have an O= in subject name.
In /usr/share/swtpm/swtpm-localca locate the lines:

- echo "cn=swtpm-localca-rootca" > "${tmp}
and
- echo "cn=swtpm-localca" > "${tmp}"

Add this line under **each**:
- echo "organization=abc" >> "${tmp}"
With abc being any string

**Comment by iadgovuser26** [comment]
The [Ek Cert Profile](https://trustedcomputinggroup.org/wp-content/uploads/Credential_Profile_EK_V2.1_R12_PUBLIC_REVIEW.pdf) , nor the certificate profile it adhears to, [rfc 5280](https://tools.ietf.org/html/rfc5280), have any required attributes on the DN within the certificate, so it is valid to have a Issuer DN without an C, O, OU, even though most certificates have these fields by convention. The Authority Key Identifier (AKI) is intended to be used as the lookup for the certificate, however the ACA is currently using the organization attribute to lookup the issuers cert. 

The [EK Certificate specification](https://trustedcomputinggroup.org/wp-content/uploads/Credential_Profile_EK_V2.1_R12_PUBLIC_REVIEW.pdf) requires the AKI, so it can be used in place of the Issuer DN for certificate lookups.  For the ACA this a fairly low level change that effects all certificate look ups. The Platform Certificate and Attestation Certificate will need to include the use of the AKI. 

The [TCG Platform cert specification](https://trustedcomputinggroup.org/wp-content/uploads/IWG_Platform_Certificate_Profile_v1p1_r19_pub_fixed.pdf) states in section 3.2.1.1 Authority Key Identifier:

 "Assign the value of “subject key identifier” from the issuer’s public key certificate, if available, else omit".

Although the field status for the AKI in table 4 of the same document implies that the field is a must. 

For the [specification defining the Attestation Certificate](https://www.trustedcomputinggroup.org/wp-content/uploads/IWG-Credential_Profiles_V1_R1_14.pdf) states the same verbiage for the Attestation Cert, however the status column in the table in that document states that the AKI is a SHOULD, not a MUST. The ACA produces an ACA and doesn't currently consume them. A Verifier may have issues of the Attestation cert does not have an AKI.

The lack of consistency in the requirement for the AKI is what probably led to use of the DN. The ACA can be changed to use the AKI as a lookup for the issuers cert. We do ,however, need to make sure the specs get updated to be a bit more consistent.

The use of AKI in place of the "O" attribute will need to broken into several issues to complete. This can be addressed after the upcoming 2.0 release.

**Comment by iadgovuser26** [comment]
This issue was addressed in PR #327.
