### ISSUE TITLE
TPM 2.0 System Tests Redesign

### ISSUE THREAD

**Issue by cyrus-dev** [nsacyber/HIRS#338]
The system tests for the TPM 2.0 need to be updated.  Specifically the Good set of scripts A6-8.  They currently fail and the reasoning is not completely known other than that the recent changes to the way the validation happens does not fit with what the scripts are expecting.  One thought is that the validation no longer duplicates on the screen.  Previously when you had failures for a certificate chain, you had one icon per certificate.  That is no longer the case, and this true in the database.  Instead of 3 SupplyChainValidation entries for 3 certificates, you have one.  

The potential change to all of this is to have each test be self contained and not depend on the previous script's results as a check in the following.

**Comment by iadgovuser26** [comment]
Met by issue Issue #422 "System Test refactor"
