### ISSUE TITLE
Old PACCOR RPM on Releases Page

### ISSUE THREAD

**Issue by m-morrone** [nsacyber/HIRS#42]
The paccor rpm on the releases page (https://github.com/nsacyber/HIRS/releases/) is a couple versions behind and lacks some later functionality, such as working with simulated TPMs.  

You may want to either update the version on the releases page or refer back to the upstream project for the latest version.

**Comment by iadgovuser26** [comment]
removed the paccor rpm from the 1.0.1 release  and replaced with a link to the paccor release page.

**Comment by apldev3** [comment]
I believe the latter of the 2 suggestions was performed, so this ticket should be good to close.
