### ISSUE TITLE
Documentation: incorrect Linux installation command for event logger

### ISSUE THREAD

**Issue by Cyborg1138** [nsacyber/HIRS#464]
https://github.com/nsacyber/HIRS/tree/master/tools/tcg_eventlog_tool

Linux install line should read: sudo yum localinstall build/distributions/tcg_eventlog_tool*.rpm and not: sudo yum localinstall build/distrobutions/tgc_rim_tool.*.rpm

**Comment by iadgovuser26** [comment]
Thank you for bringing this o our attention. The install line has been updated.
