### ISSUE TITLE
ACA Validation Report Contents Are Garbled.

### ISSUE THREAD

**Issue by Cyborg1138** [nsacyber/HIRS#499]
Fairly self-evident. Just download a validation report and it can be seen that the column cell contents do not match the column headers, and that some column headers do not contain column cell entries.

An example as viewed in Excel can be found here: https://1drv.ms/u/s!ApUl1xxOUo0lpTIhihEfYNoDKHDr?e=3pMIYD

I cannot guarantee the link will stay active for long periods.

**Comment by iadgovuser26** [comment]
This is repeatable. Looking into it....
