### ISSUE TITLE
Validation report download causes 500 error

### ISSUE THREAD

**Issue by chubtub** [nsacyber/HIRS#502]
When attempting to download a validation report from the ACA portal a 500 server error was encountered.  In this particular case all validation policies were disabled and no validation data were available on the reports page.

![image](https://user-images.githubusercontent.com/43381989/201251808-8e80bbc0-1b3a-40fa-a580-de552fceaa2e.png)

**Comment by cyrus-dev** [comment]
I was able to duplicate the issue if I didn't provide range dates.

**Comment by iadgovuser26** [comment]
Closed by PR #518
