### ISSUE TITLE
SoftwareIdentity missing Payload

### ISSUE THREAD

**Issue by cyrus-dev** [nsacyber/HIRS#525]
While investigating #517, the SoftwareIdentity object that is used in the BaseReferenceManifest file correct parses the main entries of the XML format.  However the 'Payload' element has a method getDirectoryOrFileOrProcess() that pulls the Directory/File tag elements that are children to the 'Payload' element.  This is used to create the temp object SwidResource and then used to match a BaseRIM (SwidTag) with a SupportRIM (RIMEL).  However after digging into the could this method has been returning 0 for size when the element is not empty.

1. Has there been an update to xjc/jaxb that is causing this error?  The migration code is now using Jakarta but it was a manual find and replace for 'javax.' and there needs to be an update to the .xsd file to correctly produce these files.
2. Investigate updating the xsd to produce jakarta files and maybe this resolves itself.
3. Does this affect the generation of SwidTags by the riimTool that is still using the 'javax.' libraries?

This work is already in progress.  One conclusion from this is determining if this is still the best way of doing this and should we move away.

**Comment by chubtub** [comment]
I experimented with the rimtool's validator class and creating a ResourceCollection object to hold the <Payload> data.  I had difficulty parsing the XML into an appropriate object to assign to the ResourceCollection.  I may have run into this issue when I initially wrote the validator class, which could be why the validator class goes directly to the <Directory> element and parses its child nodes.

**Comment by cyrus-dev** [comment]
> I experimented with the rimtool's validator class and creating a ResourceCollection object to hold the data. I had difficulty parsing the XML into an appropriate object to assign to the ResourceCollection. I may have run into this issue when I initially wrote the validator class, which could be why the validator class goes directly to the `<Directory>` element and parses its child nodes.

@iadgovuser58 @iadgovuser59 for issue #526, which should just be a modification of the Base RIM class.

**Comment by iadgovuser26** [comment]
Question has been resolved.
