### ISSUE TITLE
Migrate hirs_unit_tests for github actions

### ISSUE THREAD

**Issue by iadgovuser58** [nsacyber/HIRS#570]
Updating the hirs_unit_tests.yml to work with main
Also adding in a new Dockerfile corresponding to new Rocky 8.8 images located at https://github.com/orgs/nsacyber/packages/container/package/hirs%2Fhirs-rocky8-ci
(new Rocky image used in the yml file)

**Comment by iadgovuser26** [comment]
closed by [PR 571](https://github.com/nsacyber/HIRS/pull/571)
