### ISSUE TITLE
HIRS V3 Certificate data parsing issues

### ISSUE THREAD

**Issue by iadgovuser26** [nsacyber/HIRS#579]
For HIRS V3 , when uploading the HIRS certificate into the ACA Trust store for testing.  These are certificates generated for setup and loading of the ACA,
there are several issues:

1. CA/Trusted Certificates are not displaying the DN
1.  The Issuer Validation on the Certificate details page shows a red icon, even when the complete chain is uploaded. 
1. The Cert chain pem file fails to upload.
1. For the CA certs ACA should display Basic Constraints: critical, CA:TRUE
1. CRL Distribution points should be displayed, if present
1. Credential TYPE shows TCPA Trusted Platform Module Endorsement. This page probably doesn't need that field. 

java.security.cert.X509Certificate is having trouble parsing the following information for ecc trusted certificates 1) Serial Number, 2) Public Key and Algorithm and 3) Signature and Algorithm

**Comment by cyrus-dev** [comment]
ACA wasn't set up to parse chain certs

**Comment by iadgovuser26** [comment]
closed by MR 580
