### ISSUE TITLE
Migrate remaining /hirs/data/persist/ unit tests in HIRS_Utils (Pt. 1)

### ISSUE THREAD

**Issue by iadgovuser59** [nsacyber/HIRS#593]
This issue tracks migrating HIRS_Utils unit tests in the folder `HIRS_Utils/src/test/java/hirs/data/persist/` from the `master` branch to the `main` branch as part of the ongoing effort. The following files should be migrated as part of this issue:

- [x] PortalInfoTest
- [ ] ~~SupplyChainValidationSummaryTest~~ (will be saved for later; see below)
- [x] SupplyChainValidationTest
- [x] PlatformCredentialTest
- [x] CertificateTest

**Comment by iadgovuser62** [comment]
Completed migration for: PortalInfoTest, SupplyChainValidationTest, and PlatformCredentialTest and CertificateTest which were depended on. They have yet to be merged into main. SupplyChainValidationSummaryTest is pending, as it has more complex dependencies.
