### ISSUE TITLE
Check application.properties for hirs_pki_password

### ISSUE THREAD

**Issue by iadgovuser29** [nsacyber/HIRS#599]
If PKI objects are set up at a different time than the database a new PKI_PASS will be generated each time. Since db_create uses PKI_PASS to create the hibernate connector string, that password must match the one created during PKI set up.

aca_setup.sh could check if hirs_pki_password is set in application.properties. 
https://github.com/nsacyber/HIRS/blob/5c31e52828c1a177f20dba63b3472eabe9dcf63c/package/scripts/aca/aca_setup.sh#L90C2-L90C2

The check could also be performed in db_create.sh.

**Comment by iadgovuser26** [comment]
closed by [PR  602](https://github.com/nsacyber/HIRS/pull/602)
