### ISSUE TITLE
ACA Should display the Platform Certificate Holder

### ISSUE THREAD

**Issue by iadgovuser26** [nsacyber/HIRS#6]
The Platform Certificate page does not currently display the holder information (EK certificate info). The holder is defined as:
```
 Holder ::= SEQUENCE {
     baseCertificateID   [0] IssuerSerial OPTIONAL,
            -- the issuer and serial number of
            -- the holder's Public Key Certificate
     entityName          [1] GeneralNames OPTIONAL,
            -- the name of the claimant or role
     objectDigestInfo    [2] ObjectDigestInfo OPTIONAL
            -- used to directly authenticate the
            -- holder, for example, an executable
 }

 IssuerSerial ::= SEQUENCE {
     issuer     GeneralNames,
     serial     CertificateSerialNumber,
     issuerUID  UniqueIdentifier OPTIONAL
 }
```
The baseCertificateID should be displayed with a hyperlink to the EK cert page (if it exists). Per the Platform Certificaate specification, "the BaseCertificateID choice MUST be used." As such, the entityName and objectDigestInfo optional entries, valid for attribute certificates in general, are never found in Platform Certificates.

**Comment by apldev3** [comment]
#16 was merged. This can be closed at this point.
