### ISSUE TITLE
Allow for Packaging of Individual Subprojects

### ISSUE THREAD

**Issue by apldev3** [nsacyber/HIRS#63]
At the moment, the packaging scripts build all of the subprojects with no fine grain selection of packages allowed. Subprojects that are packaged into RPMs or DEBs should receive their own individualized package script that can be called from the current master packaging script to still allow for building all at one time if desired without precluding the ability to individually package subprojects.

This is would be helpful as we move forward with the Integration Testing work via Docker, because Docker will be using a shared volume among all of the Docker Containers spawned with Docker Compose. Each of these containers should be able to individually package their target subproject without stepping on the toes of the other containers also using the same Shared Volume.

**Comment by apldev3** [comment]
You're good and I must say this will likely take a while to uncouple a bunch of things that likely should never have been lumped together.

**Comment by iadgovuser26** [comment]
Placed in the backlog.
