### ISSUE TITLE
Add spot-bugs to Grade build

### ISSUE THREAD

**Issue by iadgovuser26** [nsacyber/HIRS#642]
[Spot bugs ](https://spotbugs.readthedocs.io/en/latest/gradle.html) replaces the findbugs tool used in previous builds.  This tool should be made available via a gradle task.

**Comment by cyrus-dev** [comment]
Splitting this into multiple PRs to not have a massive push.  First part just included the small set of changes in eventlog.  Next is AttestationCA that listed 202 errors.
