### ISSUE TITLE
Migration: SupplyChainValidationSummaryTest

### ISSUE THREAD

**Issue by iadgovuser62** [nsacyber/HIRS#680]
This issue: 

1) Tracks migrating the following HIRS_Utils unit test from the master branch to the main branch:

     - [ ] `HIRS_Utils/src/test/java/hirs/data/persist/SupplyChainValidationSummaryTest`

Note: The persistence components in SupplyChainValidationSummaryTest are temporarily being omitted until there is a solution for testing persistence and repositories.

2) Tracks removing unit test dependencies on other unit tests. 

     - [ ] Unit test common functions for entity objects are now moved to a new Abstract Test:
         - [ ] AbstractUserdefinedEntityTest
     - [ ] Unit tests that previously called on other tests to use common functions, now extend AbstractUserdefinedEntityTest:
         - [ ] CertificateAuthorityCredentialTest 
         - [ ] CertificateTest
         - [ ] DeviceTest
         - [ ] SupplyChainValidationSummaryTest 
         - [ ] SupplyChainValidationTest 
         - [ ] TPMInfoTest
         - [ ] DeviceInfoReportTest

3) Removes dependencies on other unit tests (test is fully reliant on itself)

     - [ ] EndorsementCredentialTest 
     - [ ] SupplyChainCredentialValidatorTest

4) Fixes checkstyles in majority of tests

EDIT: This issue originally also migrated `SupplyChainCredentialValidatorTest`, which has now been moved to [Issue 714](https://github.com/nsacyber/HIRS/issues/714).

**Comment by iadgovuser58** [comment]
Closed with PR #720
