### ISSUE TITLE
Support RIM properties causing null error

### ISSUE THREAD

**Issue by chubtub** [nsacyber/HIRS#797]
This error is encountered during firmware provisioning:
`ERROR : Null value was assigned to a property [class hirs.attestationca.persist.entity.userdefined.rim.SupportReferenceManifest.processed] of primitive type :hirs.attestationca.persist.entity.userdefined.rim.SupportReferenceManifest.processed(setter)`

**Comment by iadgovuser26** [comment]
Closed by #799
