### ISSUE TITLE
Incorrect dependencies for hirs-provisioner-tpm2 RPM

### ISSUE THREAD

**Issue by apldev4** [nsacyber/HIRS#85]
`HIRS_ProvisionerTPM2/CMakeLists.txt` claims the Ubuntu deb package depends on `libcurl4-openssl-dev`; it should actually depend on `libcurl3` which provides `libcurl.so.4`. The former package depends on the later, so it would install the right package, but it is preferable to only require what is needed.

**Comment by apldev3** [comment]
Unnecessary see MR #86

**Comment by apldev3** [comment]
Closed as won't fix.
