### ISSUE TITLE
Need support for Amazon Linux

### ISSUE THREAD

**Issue by iadgovuser26** [nsacyber/HIRS#90]
Amazon AWS has a set of supported Amazon Machine Images (AMI). "Amazon Linux" is a commonly used AMI. Amazon Linux defines the OS version within the /etc/system-release file which ,as example, currently contains "Amazon Linux release 2 (Karoo)" for the Amazon Linux  AMI. 

Currently the HIRS RPMs are  looking for similar files (e.g. /etc/rehat-release) but will not install properly on Amazon Linux. Adding a /etc/redhat-release file in the AWS instance will fix the problem for that install. To support Amazon linux a check for the /etc/system-release file should be put in the install scripts if /etc/redhat is not found.

**Comment by apldev3** [comment]
It's been deemed that the scope for this was to simply be able to install the RPM on Amazon Linux and not necessarily to do all the building and packaging on Amazon Linux. As discovered in the pull request, the ability to build/package on Amazon Linux has some issues that would need ironed out in a follow-on issue, but the actual install of a package that was built on CentOS7 should be fairly easy.
