### ISSUE TITLE
log4cplus error printed during provisioning.

### ISSUE THREAD

**Issue by iadgovuser26** [nsacyber/HIRS#95]
When provisioning a tpm2 log4cplus prints an initialization error 
```
TPM 2.0 detected.
log4cplus:ERROR No appenders could be found for logger (root).
log4cplus:ERROR Please initialize the log4cplus system properly.--> Provisioning
----> Collecting endorsement credential from TPM
----> Creating attestation key
----> Collecting platform credential from TPM
...
```

**Comment by apldev3** [comment]
This only shows up if someone uses the Tagged 1.0.3 release without any additional configuration of `/etc/hirs/logging.properties` after the install.

These errors show up when the `root.level` of the aforementioned `logging.properties` is set to `error`. If you remove the `error` and just leave the property blank, then the error goes away. This is a workaround in the interim while we figure out why this is the case.

**Comment by apldev3** [comment]
I've also confirmed that this will occur outside of the `1.0.3` release if you go set the `root.level` to `error` in `logging.properties`.

**Comment by apldev3** [comment]
At this point, I can also say it's not exclusive to the "error" log level. Indeed if you add anything to the `root.level` key then it will throw the error.
